### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by kgilmer** [practicalli/regolith-solarized-light#1]
Where do I get:
* Solarized-Light
* Faba
* /usr/share/backgrounds/practicalli-desktop-redux.png

thanks in advance! :smile:

**Comment by practicalli-johnny** [comment]
I have updated the README to include more details.

In summary:
- [Solarized Light](https://www.gnome-look.org/p/1309911/) - any GTK theme can be used, it affects only GTK apps
- [Faba](https://snwh.org/moka/download) - or use any GTK icons you like, it only affects GTK applications
- [Practicalli background image](https://github.com/practicalli/graphic-design/blob/master/practicalli-desktop-redux.png) - use any desktop background you wish, defined in `Xresources-theme`, for example the current Regolith defalt image `/usr/share/backgrounds/regolith-structure-7.png`

**Comment by kgilmer** [comment]
Thanks @jr0cket .  Sorry I didn't close this sooner.  I spent some time today looking at integrating your theme directly into Regolith.  However, I cannot find a good Solarized Light GTK theme that is packaged in Debian.  I cannot add things to Regolith that are not packaged and so would have to do it myself.  I may get to it but not for this next release.  If you happen to find a good gtk theme that is packaged, please let me know!
